import type { z } from 'zod';
import type { authSessionSchema, authUserSchema, currencySchema, errorResponseSchema, walletBalanceSchema, walletSchema } from '../schemas/common.js';
import type { loginRequestSchema, registerRequestSchema } from '../schemas/auth.js';
import type { createDepositRequestSchema, depositSchema } from '../schemas/deposits.js';
import type { createTransferRequestSchema, financialOperationSchema, transferSchema } from '../schemas/transfers.js';
import type { brlExchangeRateSchema, brlExchangeRatesSchema, createExchangeConversionRequestSchema, createExchangeQuoteRequestSchema, exchangeConversionSchema, exchangeQuoteSchema } from '../schemas/exchange.js';
import type { statementDetailSchema, statementItemSchema, statementListSchema, statementQuerySchema } from '../schemas/statement.js';
import type { reversalRequestSchema, reversalResponseSchema } from '../schemas/reversals.js';

export type Currency = z.infer<typeof currencySchema>;
export type ErrorResponseDto = z.infer<typeof errorResponseSchema>;
export type AuthUserDto = z.infer<typeof authUserSchema>;
export type AuthSessionDto = z.infer<typeof authSessionSchema>;
export type RegisterRequestDto = z.input<typeof registerRequestSchema>;
export type LoginRequestDto = z.input<typeof loginRequestSchema>;
export type WalletBalanceDto = z.infer<typeof walletBalanceSchema>;
export type WalletDto = z.infer<typeof walletSchema>;
export type CreateDepositRequestDto = z.input<typeof createDepositRequestSchema>;
export type DepositDto = z.infer<typeof depositSchema>;
export type FinancialOperationDto = z.infer<typeof financialOperationSchema>;
export type CreateTransferRequestDto = z.input<typeof createTransferRequestSchema>;
export type TransferDto = z.infer<typeof transferSchema>;
export type CreateExchangeQuoteRequestDto = z.input<typeof createExchangeQuoteRequestSchema>;
export type CreateExchangeConversionRequestDto = z.input<typeof createExchangeConversionRequestSchema>;
export type ExchangeQuoteDto = z.infer<typeof exchangeQuoteSchema>;
export type ExchangeConversionDto = z.infer<typeof exchangeConversionSchema>;
export type BrlExchangeRateDto = z.infer<typeof brlExchangeRateSchema>;
export type BrlExchangeRatesDto = z.infer<typeof brlExchangeRatesSchema>;
export type StatementItemDto = z.infer<typeof statementItemSchema>;
export type StatementListDto = z.infer<typeof statementListSchema>;
export type StatementDetailDto = z.infer<typeof statementDetailSchema>;
export type StatementQueryDto = z.input<typeof statementQuerySchema>;
export type ReversalRequestDto = z.input<typeof reversalRequestSchema>;
export type ReversalDto = z.infer<typeof reversalResponseSchema>;
