export const errorCodes = [
  'VALIDATION_ERROR',
  'UNAUTHORIZED',
  'FORBIDDEN',
  'NOT_FOUND',
  'EMAIL_ALREADY_EXISTS',
  'INVALID_CREDENTIALS',
  'UNSUPPORTED_CURRENCY',
  'INSUFFICIENT_FUNDS',
  'WALLET_NOT_FOUND',
  'RECIPIENT_NOT_FOUND',
  'SAME_TRANSFER_PARTICIPANT',
  'DEPOSIT_NOT_FOUND',
  'DEPOSIT_ALREADY_CONFIRMED',
  'QUOTE_NOT_FOUND',
  'IDEMPOTENCY_CONFLICT',
  'DUPLICATE_REVERSAL',
  'QUOTE_EXPIRED',
  'FINANCIAL_OPERATION_NOT_FOUND',
  'FINANCIAL_OPERATION_NOT_REVERSIBLE',
  'FINANCIAL_OPERATION_ALREADY_REVERSED',
  'EXTERNAL_SERVICE_FAILURE',
  'INTERNAL_ERROR'
] as const;

export type ErrorCode = (typeof errorCodes)[number];
